Class 01 hw7 yu nyuk
kccistc/intel-04 pull request #298
Opened 2024-05-31 08:02 UTC by YuNyuk

과제 제출합니다

2024-06-02 05:50 UTC, J-WBaek requested changes
hw5에 올라가있는 .h5 파일은 지우고 올려주세요.

2024-06-05 06:38 UTC, J-WBaek approved these changes

2024-06-05 06:38 UTC, J-WBaek requested changes
.h5 파일 지우고 다시 올려주세요.

2024-06-10 04:07 UTC, YuNyuk commented
다시 업로드했습니다!

2024-06-10 06:36 UTC, J-WBaek approved these changes

2024-06-10 06:48 UTC, merged