[Class01 HW#7] python 과제 및 math 실습 - 정용재
kccistc/intel-04 pull request #308
Opened 2024-05-31 08:07 UTC by eolgaemi

[Class01 HW#7] python 과제 및 math 실습 - 정용재

2024-06-02 05:21 UTC, J-WBaek requested changes
해당 마일스톰 내용에 이슈링크 있습니다.
이슈에서 폴더 구성, 이름 확인해주세요.
https://github.com/kccistc/intel-04/milestone/6

Day07과제에서 transpose를 사용하지 않으셨네요.
transpose를 통해 (1, 3, 700, 526) 형태로 만들어 보세요.

2024-06-10 04:47 UTC, eolgaemi commented
transpose 부분 수정했습니다!

2024-06-10 06:41 UTC, J-WBaek requested changes
1. 폴더 구성 issue에 있는 대로 변경해주세요.
2. hw6에 해당하는  0530_homework 안에 .ipynb_checkpoint 는 지구오 올려주세요.
3. hw6의 transpose 부분이

image_batch = np.transpose(image)
image_batch = np.expand_dims(image, axis=0)

에서

image_batch = np.transpose(image, (2,0,1))
image_batch = np.expand_dims(image, axis=0)

으로 변경해보세요.

2024-06-10 07:32 UTC, J-WBaek approved these changes

2024-06-10 07:32 UTC, merged